---
title: "Journal papers with peer review"
output: html_document
---

<hr>

- Javier Cara, David Escolano-Margarit, Amadeo Benavent-Climent. *Estimation of modal parameters of structures subjected to known base accelerations: Application to shake table tests*. Soil Dynamics and Earthquake Engineering, Volume 196 (2025). https://doi.org/10.1016/j.soildyn.2025.109437

- Daniel Bouzon Nagem Assad, Patricia Gomes Ferreira da Costa, Thaís Spiegel, Javier Cara, Miguel Ortega-Mier & Alfredo Monteiro Scaff. *Comparing the current short‐term cancer incidence prediction models in Brazil with state‐of‐the‐art time‐series models*.  Scientific  Reports,  14, Article number: 4566 (2024). https://doi.org/10.1038/s41598-024-55230-2

- Assad, D.B.N., Cara, J. & Ortega-Mier, M. *Comparing Short-Term Univariate and Multivariate Time-Series Forecasting Models in Infectious Disease Outbreak*. Bull Math Biol 85, 9 (2023). https://doi.org/10.1007/s11538-022-01112-5.

- E. Caro, J. Juan, J. Cara. *Periodically correlated models for short-term electricity load forecasting*. Applied Mathematics and Computation, Volume 364, 1 January 2020, 124642. https://doi.org/10.1016/j.amc.2019.124642.

- Javier Cara. *Modal identification of structures from input/output data using the expectation–maximization algorithm and uncertainty quantification by mean of the bootstrap*. Structural Control and Health Monitoring, Volume 26, Issue 1, January 2019, https://doi.org/10.1002/stc.2272.

- Javier Cara. *Computing the modal mass from the state space model in combined experimental–operational modal analysis*. Journal of Sound and Vibration, Volume 370, 26 May 2016, Pages 94-110, http://dx.doi.org/10.1016/j.jsv.2016.01.043.

- F. Javier Cara, J. Juan, E. Alarcón. *Estimating the modal parameters from multiple measurement setups using a joint state space model*. Mechanical Systems and Signal Processing. Vol. 43, p. 171-191, 2014, http://dx.doi.org/10.1016/j.ymssp.2013.09.012.

- F. Javier Cara, J. Juan, E. Alarcón, E. Reynders, G. De Roeck. *Modal contribution and state-space order selection in operational modal analysis*. Mechanical Systems and Signal Processing. Vol. 38, p. 276-298, 2013, http://dx.doi.org/10.1016/j.ymssp.2013.03.001.

- F. Javier Cara, J. Carpio, J. Juan, E. Alarcón. *An approach to Operational Modal Analysis using the Expectation Maximization Algorithm*. Mechanical Systems and Signal Processing. Vol. 31, p. 109-129, August 2012, http://dx.doi.org/10.1016/j.ymssp.2012.04.004.